/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.jomof.cxx

import kotlin.test.Test
import org.gradle.testkit.runner.GradleRunner
import org.junit.Rule
import org.junit.rules.TemporaryFolder
import java.io.File

class SimplestProjectTest {
    @get:Rule val tempFolder = TemporaryFolder()

    private val projectDir by lazy { tempFolder.root }
    private val buildFile by lazy { projectDir.resolve("build.gradle") }
    private val settingsFile by lazy { projectDir.resolve("settings.gradle") }

    @Test fun `can run task`() {
        projectDir.resolve("obj/hello.o.d").delete()
        projectDir.resolve("hello.h").writeText("""
            #define MESSAGE "Hello, World!\n"
            
        """.trimIndent())
        projectDir.resolve("hello.c").writeText("""
            #include <stdio.h>
            #include "hello.h"
            
            int main() {
               printf(MESSAGE);
               return 0;
            }
            
        """.trimIndent())
        settingsFile.writeText("")
        buildFile.writeText("""
            plugins {
                id('com.github.jomof.cxx.core') version '0.0.1'
            }
            cxx {
                // Create a rule for compiling a .c file into a .o file
                var compile = rule {
                    description = "Building ${'$'}out"
                    depfile = "${'$'}{out}.d"
                    command = "/usr/bin/clang ${'$'}cflags -c ${'$'}in -o ${'$'}out -MD -MF ${'$'}depfile"
                }
                // Create a rule for linking .o file into executable
                var link = rule {
                    description = "Linking ${'$'}out"
                    command = "/usr/bin/clang ${'$'}in -o ${'$'}out"
                }
                // Compile hello.c into obj/hello.o
                compile {
                    in = "hello.c"
                    out = "obj/hello.o"
                    cflags = "-Weverything"
                }
                // Link obj/hello.o into bin/hello executable
                link {
                    in = "obj/hello.o"
                    out = "bin/hello"
                }
            }

            """.trimIndent())

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("--stacktrace", "--configuration-cache", "wrapper", "bin-hello", "clean")
        runner.withProjectDir(projectDir)
        val result = runner.build()
        publishDemo(projectDir, "simplest",
            """
                This project demonstrates the simplest possible C/C++ build. It expects
                'clang' to be on the path.
            """.trimIndent())
        }
}
