/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.jomof.cxx

import kotlin.test.Test
import org.gradle.testkit.runner.GradleRunner
import org.junit.Rule
import org.junit.rules.TemporaryFolder
import java.io.File

class SimplestProjectTest {
    @get:Rule val tempFolder = TemporaryFolder()

    private val projectDir by lazy { tempFolder.root }
    private val buildFile by lazy { projectDir.resolve("build.gradle") }
    private val settingsFile by lazy { projectDir.resolve("settings.gradle") }

    @Test fun `can run task`() {
        projectDir.resolve("hello.c").writeText("""
            #include <stdio.h>
            int main() {
               printf("Hello, World!\n");
               return 0;
            }
            
        """.trimIndent())
        val localRepo = File("../local-plugin-repository").absolutePath
        settingsFile.writeText("""
            pluginManagement {
                repositories {
                    maven { url '$localRepo' }
                    mavenCentral()
                }
            }
        """.trimIndent())
        buildFile.writeText("""
            plugins {
                id('com.github.jomof.cxx.core') version '0.0.1'
            }
            cxx {
                var compile = rule {
                    description = "Building ${'$'}out"
                    command = "clang ${'$'}cflags -c ${'$'}in -o${'$'}out"
                }
                var link = rule {
                    description = "Linking ${'$'}out"
                    command = "clang ${'$'}in -o${'$'}out"
                 }
                compile {
                    in = "hello.c"
                    out = "obj/hello.o"
                    cflags = "-Weverything"
                }
                link {
                    in = "obj/hello.o"
                    out = "bin/hello"
                }
            }
            """.trimIndent())

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("wrapper", "bin-hello")
        runner.withProjectDir(projectDir)
        val result = runner.build()
        println("$projectDir")
        println("")
        val localCopy = File("../demo/simplest").absoluteFile
        localCopy.deleteRecursively()
        localCopy.mkdirs()
        projectDir.copyRecursively(localCopy)
    }
}
