{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.jomof",
    "module": "plugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-0.0.1.jar",
          "url": "plugin-0.0.1.jar",
          "size": 32644,
          "sha512": "8b8bb4ffa7818732815e0ac4b35e2ef379dfde9f7d49b969afdbec355f89e9696e69312549c847765ffeb61e38637229413151c720205582da08c613bad9171d",
          "sha256": "f8460f7e30c45f8010b2d010c10e1b4b32078c951941784e325fbbdc0384607a",
          "sha1": "34f212354ccad20dd010ddbf612a54279a1a7326",
          "md5": "6e3970b007f012041f7351e6464d6bf6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.6.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-0.0.1.jar",
          "url": "plugin-0.0.1.jar",
          "size": 32644,
          "sha512": "8b8bb4ffa7818732815e0ac4b35e2ef379dfde9f7d49b969afdbec355f89e9696e69312549c847765ffeb61e38637229413151c720205582da08c613bad9171d",
          "sha256": "f8460f7e30c45f8010b2d010c10e1b4b32078c951941784e325fbbdc0384607a",
          "sha1": "34f212354ccad20dd010ddbf612a54279a1a7326",
          "md5": "6e3970b007f012041f7351e6464d6bf6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-0.0.1-javadoc.jar",
          "url": "plugin-0.0.1-javadoc.jar",
          "size": 261,
          "sha512": "2f5f446676cfb7e48a821acfe6830d60a820b574c731a9e4f27c22104d063f720f374b7827da4888ca2262e8b2a9c225121a3d411ee47bb8e49fa5eee38828dd",
          "sha256": "94d098591058eac1936e6a157e462a3b7b2e07b619e01def43a1accaee712eff",
          "sha1": "625413c1a0c971507e71d87e54f8e73093c624e2",
          "md5": "95d75785f70c8d14913a38be5e1fa67c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-0.0.1-sources.jar",
          "url": "plugin-0.0.1-sources.jar",
          "size": 11171,
          "sha512": "c90dd726c3a8368e91b8797de4bfbca516bbe8f416635b43460196012d2c2b4b23bfc8bcccac81653428dd68450fd1674ce4275d5cbc98a2f55dca8226365c77",
          "sha256": "71ea5ed818b07eb559c5463129204010b57451893425272e2762cd74f1ad4833",
          "sha1": "246c55d3c38d80eb0703f10b1200c70509383c3f",
          "md5": "b9c0543cc205b3f37c5c08db487a4c08"
        }
      ]
    }
  ]
}
