{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.jomof",
    "module": "plugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-0.0.1.jar",
          "url": "plugin-0.0.1.jar",
          "size": 65637,
          "sha512": "a28cacf6b33ca4880cbb7cd263a37a683dd36ef1334e7e00dc4f80fe9d0dc22f70a485174a37aeed4c793575d552bfaa81402f2f316e7d55ee63f7ddfeb63a67",
          "sha256": "aeecef2d59cbee3283f0989fdff3bdaad29ed04f6052ca3e80fb3b6b6d5f5e08",
          "sha1": "e5731b32bba170ef07e3d678554308ab14c84a36",
          "md5": "c7b59c17dd7b9f1a40b15e807b5e2c35"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.6.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-0.0.1.jar",
          "url": "plugin-0.0.1.jar",
          "size": 65637,
          "sha512": "a28cacf6b33ca4880cbb7cd263a37a683dd36ef1334e7e00dc4f80fe9d0dc22f70a485174a37aeed4c793575d552bfaa81402f2f316e7d55ee63f7ddfeb63a67",
          "sha256": "aeecef2d59cbee3283f0989fdff3bdaad29ed04f6052ca3e80fb3b6b6d5f5e08",
          "sha1": "e5731b32bba170ef07e3d678554308ab14c84a36",
          "md5": "c7b59c17dd7b9f1a40b15e807b5e2c35"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-0.0.1-javadoc.jar",
          "url": "plugin-0.0.1-javadoc.jar",
          "size": 261,
          "sha512": "2f5f446676cfb7e48a821acfe6830d60a820b574c731a9e4f27c22104d063f720f374b7827da4888ca2262e8b2a9c225121a3d411ee47bb8e49fa5eee38828dd",
          "sha256": "94d098591058eac1936e6a157e462a3b7b2e07b619e01def43a1accaee712eff",
          "sha1": "625413c1a0c971507e71d87e54f8e73093c624e2",
          "md5": "95d75785f70c8d14913a38be5e1fa67c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-0.0.1-sources.jar",
          "url": "plugin-0.0.1-sources.jar",
          "size": 17361,
          "sha512": "428af6bac07707016bb9bae328c07a497eaac84c4dcfd715e7ab9abe4fc8f0893a054eed074c8ccfee77e229e49ac248bebd8444ca784eb3bfb982e41fb7ef72",
          "sha256": "a8b63d59c88f1520923b0be9a1a6991858fd6be6b1b2d9b9343ba830b62ec14b",
          "sha1": "14c60c264c240cb7dd01dba86e6f3db95c75a17b",
          "md5": "5d0798a7b81da93388f75809ee6d3dc1"
        }
      ]
    }
  ]
}
