{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.jomof",
    "module": "plugin",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-0.0.1.jar",
          "url": "plugin-0.0.1.jar",
          "size": 32734,
          "sha512": "9ac8aa1cc86184ae13946101f1a214b3eeb00ddc898cb7154f70cd8f6d0a92a8890064ed9f20a1bf4264d0f175b4ff07acf5b1e6108bee176718492c48f288f3",
          "sha256": "e2d3f575a28a30d49888907d2014135a265cab998fe418c628aaec1d845191f9",
          "sha1": "8cb4f0b2e1efbbeac131d81805b62ef5703b5a17",
          "md5": "ffef18a9f9faa0bc667e88fa08fea472"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.6.21"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-0.0.1.jar",
          "url": "plugin-0.0.1.jar",
          "size": 32734,
          "sha512": "9ac8aa1cc86184ae13946101f1a214b3eeb00ddc898cb7154f70cd8f6d0a92a8890064ed9f20a1bf4264d0f175b4ff07acf5b1e6108bee176718492c48f288f3",
          "sha256": "e2d3f575a28a30d49888907d2014135a265cab998fe418c628aaec1d845191f9",
          "sha1": "8cb4f0b2e1efbbeac131d81805b62ef5703b5a17",
          "md5": "ffef18a9f9faa0bc667e88fa08fea472"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-0.0.1-javadoc.jar",
          "url": "plugin-0.0.1-javadoc.jar",
          "size": 261,
          "sha512": "2f5f446676cfb7e48a821acfe6830d60a820b574c731a9e4f27c22104d063f720f374b7827da4888ca2262e8b2a9c225121a3d411ee47bb8e49fa5eee38828dd",
          "sha256": "94d098591058eac1936e6a157e462a3b7b2e07b619e01def43a1accaee712eff",
          "sha1": "625413c1a0c971507e71d87e54f8e73093c624e2",
          "md5": "95d75785f70c8d14913a38be5e1fa67c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-0.0.1-sources.jar",
          "url": "plugin-0.0.1-sources.jar",
          "size": 11168,
          "sha512": "ac0d57f32c14dada5688ad0537ad4fcfa75e49a86f9138c9b483c73df22d7027f748de9e39b9b23096f13595c62672b62616cd45cbe7e248eb7d8a718d706224",
          "sha256": "7a289c366fc3776124cabdcde18da63565d6152128d13af63f34271e82cad77b",
          "sha1": "b2bf872809697557739e36de9e4dcc3d96050dc3",
          "md5": "6e1d8dc4ae5f7b39ca51cd217a8aebd0"
        }
      ]
    }
  ]
}
